name: Test Commit & Push to Repo

on:
  push:
  workflow_dispatch:

jobs:
  test-upload-to-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 必须开这个权限才能推回仓库
    steps:
      - uses: actions/checkout@v4

      # 生成一个测试文件
      - name: Create test file
        run: |
          echo "测试自动提交 $(date)" > auto-test-file.txt
          echo "This file is auto committed by GitHub Action" >> auto-test-file.txt

      # Git 配置
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -a -m "Update $(date +'%Y-%m-%d %H:%M:%S')"
          git push
