name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'  # 只有打 tag 才会执行发布
        with:
          files: Release.txt  # 这里必须和上面生成的文件名一致
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 必须加这个
